
complete -c cpr -s a -l archive --description "Same as -dpR"
complete -c cpr -s b -l backup --description "Make backup of each existing destination file" -a "none off numbered t existing nil simple never"
complete -c cpr -l copy-contents --description "Copy contents of special files when recursive"
complete -c cpr -s d --description "Same as --no-dereference --preserve=link"
complete -c cpr -s f -l force --description "Do not prompt before overwriting"
complete -c cpr -s i -l interactive --description "Prompt before overwrite"
complete -c cpr -s H --description "Follow command-line symbolic links"
complete -c cpr -s l -l link --description "Link files instead of copying"
complete -c cpr -l strip-trailing-slashes --description "Remove trailing slashes from source"
complete -c cpr -s S -l suffix -r --description "Backup suffix"
complete -c cpr -s t -l target-directory --description "Target directory" -x -a "(__fish_complete_directories (commandline -ct) 'Target directory')"
complete -c cpr -s u -l update --description "Do not overwrite newer files"
complete -c cpr -s v -l verbose --description "Verbose mode"
complete -c cpr -l help --description "Display help and exit"
complete -c cpr -l version --description "Display version and exit"
complete -c cpr -s L -l dereference --description "Always follow symbolic links"
complete -c cpr -s P -l no-dereference --description "Never follow symbolic links"
complete -c cpr -s p  --description "Same as --preserve=mode,ownership,timestamps"
complete -c cpr -l preserve --description "Preserve the specified attributes and security contexts, if possible" -a "mode ownership timestamps links all"
complete -c cpr -l no-preserve -r --description "Don't preserve the specified attributes" -a "mode ownership timestamps links all"
complete -c cpr -l parents --description "Use full source file name under DIRECTORY"
complete -c cpr -l remove-destination --description "Remove each existing destination file before attempting to open it (contrast with --force)"
complete -c cpr -l sparse -r --description "Control creation of sparse files" -a "always auto never"
complete -c cpr -s s -l symbolic-link --description "Make symbolic links instead of copying"
complete -c cpr -s T -l no-target-directory --description "Treat DEST as a normal file"
complete -c cpr -s x -l one-file-system --description "Stay on this file system"
complete -c cpr -s X -l context -r --description "Set security context of copy to CONTEXT"

