
set -x INFINALITY_FT_FILTER_PARAMS "11e-2 22e-2 38e-2 22e-2 11e-2"
set -x INFINALITY_FT_STEM_ALIGNMENT_TYPE medium
set -x INFINALITY_FT_AUTOFIT_STEM_SNAP_LIGHT true
set -x INFINALITY_FT_AUTOFIT_EMBOLDEN_LIGHT true
set -x INFINALITY_FT_PSEUDO_GAMMA "9 7e-1"
set -x INFINALITY_FT_AUTOFIT_ADJUST_HEIGHTS true
set -x INFINALITY_FT_ENHANCED_EMBOLDEN true
set -x INFINALITY_FT_EMBOLDEN_MAINTAIN_WIDTH true
set -x INFINALITY_FT_AUTO_AUTOHINT true

# vim:ts=4:sw=4:et:ft=fish:
